- name: Create and configure website
  hosts: all
  become: true
  tasks:
  - name: Install Apache web server
    apt:
      name: apache2
      state: present
  - name: Create index.html file
    copy:
      content: "Makarios Nassef - Welcome to my website!"
      dest: /var/www/html/index.html
  - name: Start Apache web server
    service:
      name: apache2
      state: started
  - name: Check that Apache is running
    shell: systemctl is-active apache2
    register: result
  - name: Fail if Apache is not running
    fail:
      msg: "Apache is not running"
    when: result.stdout != "active"
