---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: {{ .Values.matchLabels.app }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type}}
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: {{ .Values.matchLabels.app }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
  type: NodePort
